function sys = get_system2(params)

a31 = -params.Mc*params.Dt*params.g/params.Jsw;
a32 = -(params.g*params.Mc*params.Rm*params.r^2*params.Jsw+params.Mc...
    *params.Dt*params.Rm*params.r^2*params.g*params.Msw*params.Dc)/...
    (params.Rm*params.r^2*params.Jsw*params.Mc);
a33 = (-params.Jsw*params.eta_g*params.Kg^2*params.eta_m*params.Kt*...
    params.Km-params.Jsw*params.Beq*params.Rm*params.r^2-params.Mc*...
    params.Dt^2*params.eta_g*params.Kg^2*params.eta_m*params.Kt*...
    params.Km-params.Mc*params.Dt^2*params.Beq*params.Rm*params.r^2)...
    /(params.Rm*params.r^2*params.Jsw*params.Mc);
a34 = -(params.Dt*params.Bsw)/params.Jsw;
a41 = -(params.g*params.Mc)/params.Jsw;
a42 = (params.g*params.Msw*params.Dc)/params.Jsw;
a43 = -(params.eta_g*params.Kg^2*params.eta_m*...
    params.Kt*params.Km*params.Dt+params.Beq*...
    params.Rm*params.r^2*params.Dt)/(params.Rm*params.r^2*params.Jsw);
a44 = -params.Bsw/params.Jsw;
b3 = (params.Jsw*params.eta_g*params.Kg*params.eta_m*params.Kt*...
    params.r+params.Mc*params.Dt^2*...
    params.eta_g*params.Kg*params.eta_m*params.Kt*...
    params.r)/(params.Rm*params.r^2*params.Jsw*params.Mc);
b4 = (params.eta_g*params.Kg*params.eta_m*...
    params.Kt*params.Dt)/(params.r*params.Rm*params.Jsw);

A = [0,0,1,0;
    0,0,0,1;
    a31, a32, a33, a34;
    a41, a42, a43, a44];
B = [0;0;b3;b4];

C =[1,0,0,0;0,1,0,0];
D = zeros(2,1);
sys = ss(A,B,C,D);
end

